### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by isxuyuan** [chaserw/Student-Information-Management-System#1]
请问你使用的IDE是eclipse吧，可为啥我clone你的代码在电脑上运行不了阿？

**Comment by yan-sheng-li** [comment]
咋下载

**Comment by 27ovo** [comment]
下载啥？？代码吗？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaserw/Student-Information-Management-System"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月26日(星期五) 下午5:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [chaserw/Student-Information-Management-System] 请教一下 (#1)





 
咋下载
